// <auto-generated />
namespace Atomac_Sah_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cetvrta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cetvrta));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011709060_Cetvrta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
